#!/bin/bash
#
source VAR

cmdtorun="api restart"

if [ $use_dns = "true" ]
then
ssh -q admin@${host} "$cmdtorun"
echo "waiting for server to finish processinging startup"
sleep 16
ssh -q admin@${host} "api status"
sleep 10
echo "Ready. If this is a new manager, run first.config.app"
else
echo "get a domain in route53, I'm tired of IP"
exit 1
fi
exit 0

