#!/bin/bash
. VAR
if [ -z "$1" ]
  then
BUCKET_NAME="${domain}.cpdeploy"
else
BUCKET_NAME="${1}.cpdeploy"
fi
echo "Checking if S3 backup bucket exists..."   
S3_CHECK=$(aws s3 ls "s3://${BUCKET_NAME}" 2>&1)  
#Some sort of error happened with s3 check 
if [ $? != 0 ]  
then 
  NO_BUCKET_CHECK=$(echo $S3_CHECK | grep -c 'NoSuchBucket') 
  if [ $NO_BUCKET_CHECK = 1 ]; then 
    echo "Bucket does not exist, attempting to create one."
    aws s3 mb s3://${BUCKET_NAME}  
    echo "run 'backmeup' to save your running config during your session"
    echo 
  else 
    echo "Error checking S3 Bucket" 
    echo "$S3_CHECK" 
    exit 1 
  fi 
else
  echo "Bucket exists" 
  echo "backing up to ${BUCKET_NAME}"
  aws s3 cp /cpdeploy/VAR s3://${BUCKET_NAME}/VAR
  aws s3 cp /cpdeploy/app/domain s3://${BUCKET_NAME}/domain
  aws s3 cp /cpdeploy/debug.output s3://${BUCKET_NAME}/debug.output
  aws s3 sync /root s3://${BUCKET_NAME}/root --exclude "*credentials" --delete
  aws s3 sync /cpdeploy/gw/output s3://${BUCKET_NAME}/gwoutput --delete
  aws s3 sync /cpdeploy/mg/output s3://${BUCKET_NAME}/mgoutput --delete
  fi 
