#!/bin/bash
#
if [ -z "$1" ]
  then
echo ""
    echo "give a name for your management station, like $0 greta"
    echo "you do not need to specify the domain"
    echo "or use the IP if you are not using DNS"
echo ""
exit
fi

source VAR

if [ $use_dns = "true" ]
then

ssh admin@${1}.${domain} "cpstop"
sleep 5
ssh admin@${1}.${domain} "cpdb scheme_adjust"
sleep 3
ssh admin@${1}.${domain} "cpstart"

else
IP=$(awk '/PublicIpAddress/ {print $2;}' ${mgout}/${1}-pubip | sed 's/"//g' | sed 's/,//g')

ssh admin@${IP} "cpstop"
sleep 5
ssh admin@${IP} "cpdb scheme_adjust"
sleep 3
ssh admin@${IP} "cpstart"
fi
exit 0
