#!/bin/bash

. VAR

if [ -z "$1" ]
  then
BUCKET_NAME="${domain}.cpdeploy"
else
BUCKET_NAME="${1}.cpdeploy"
fi

echo "Checking if S3 backup bucket exists..."   
S3_CHECK=$(aws s3 ls "s3://${BUCKET_NAME}" 2>&1)  
#Some sort of error happened with s3 check
if [ $? != 0 ] 
then  
  NO_BUCKET_CHECK=$(echo $S3_CHECK | grep -c 'NoSuchBucket') 
  if [ $NO_BUCKET_CHECK = 1 ]; then 
    echo "Bucket does not exist, can't find backup " 
    echo "run 'backmeup' to save your running config during this session"
    echo
  else
    echo "Error checking S3 Bucket"
    echo "$S3_CHECK"  
    exit 1   
  fi 
else
  echo "Bucket exists" 
  echo "restoring from backup ${BUCKET_NAME}"
  aws s3 cp s3://${BUCKET_NAME}/VAR /cpdeploy/VAR
  aws s3 cp s3://${BUCKET_NAME}/domain /cpdeploy/app/domain
  aws s3 cp s3://${BUCKET_NAME}/debug.output /cpdeploy/debug.output
  aws s3 sync s3://${BUCKET_NAME}/root /root --exclude "*credentials" 
  aws s3 sync s3://${BUCKET_NAME}/gwoutput /cpdeploy/gw/output --delete
  aws s3 sync s3://${BUCKET_NAME}/mgoutput /cpdeploy/mg/output --delete
chmod -R go-rwx /root/.ssh
  fi 
