#!/bin/bash
#
cmdtorun="cat /var/log/cloud-user-data"

source VAR
echo "${host} is initalizing "
sleep 360
echo "${host} is self configuring. "
declare -a stat
stat=( "starting up" "looking for first config" )

if [ $use_dns = "true" ]
then
	while [ "${stat[-1]}" != "completed!" ] ; do
sleep 45
declare -a stat=(`ssh -q admin@${host} "$cmdtorun"`)
echo " . " 
done
sleep 165
echo "${host} is ready: ${stat[-1]} " 
else
echo "get a domain in route53, I'm tired of IP"
exit 1
fi
date > ${mgout}/.isready
rm -rf ${mgout}/.islaunched
exit 0

