#!/bin/bash
#
#
crd="mkdir -p"
keyloc="/root/.ssh"

eval "${crd} ${keyloc}"
eval "chmod -R go-rwx ${keyloc}"

SESSIONKEY=(`eval hexdump -n 4 -v -e \'\/1 \"%02X\"\' /dev/urandom`)
echo " getting session key $SESSIONKEY and putting it in ${keyloc}/mykey"
eval echo -n "${SESSIONKEY}" > ${keyloc}/mykey
eval openssl genrsa 2048 > ${keyloc}/${SESSIONKEY}.pem
eval openssl rsa -in ${keyloc}/${SESSIONKEY}.pem -pubout > ${keyloc}/${SESSIONKEY}.pub
PUBKEY=(`cat ${keyloc}/${SESSIONKEY}.pub | grep -v PUBLIC | tr -d '\n'`)
 
echo "$SESSIONKEY"
echo "pubmaterial"
echo "${PUBKEY[@]}"
eval echo "Host \*" > $keyloc/config
eval echo "     User admin" >> ${keyloc}/config
eval echo "     IdentityFile ${keyloc}/${SESSIONKEY}.pem" >> ${keyloc}/config
eval echo "     StrictHostKeyChecking no" >> ${keyloc}/config
cat ${keyloc}/config
eval "chmod -R go-rwx ${keyloc}"
EKEY=(`aws ec2 import-key-pair --region us-east-1  --key-name ${SESSIONKEY} --public-key-material ${PUBKEY[@]}`)
WKEY=(`aws ec2 import-key-pair --region us-west-1  --key-name ${SESSIONKEY} --public-key-material ${PUBKEY[@]}`)
eval echo "${EKEY[@]}" > ${keyloc}/mykey.east
eval echo "${WKEY[@]}" > ${keyloc}/mykey.west

exit 0


