#!/bin/bash
if [ -z "$1" ]
  then
echo ""
    echo "Just give the number designation for the gateway, like $0 1"
    echo "This will build policy"
echo ""
exit
fi

source VAR
vpcid=$(awk '/VpcId/ {print $2;}' ${out}/${1}/vpc | sed 's/"//g' | sed 's/,//g')
subnetid0=$(awk '/SubnetId/ {print $2;}' ${out}/${1}/subnet0 | sed 's/"//g' | sed 's/,//g')
IP=$(awk '/PublicIpAddress/ {print $2;}' ${out}/${1}/pubip | sed 's/"//g' | sed 's/,//g')
subid=(`cat ${out}/${1}/id`)
baseurl=https://$host/web_api
curl_cmd="curl --silent --insecure -X POST"

SID=`${curl_cmd} -H "Content-Type: application/json" -d @- $baseurl/login <<. | awk -F\" '/sid/ {print $4}'
{
  "user":"$username" ,
  "password":"$password" ,
  "session-name":"API"
}
.`
# Login complete, add objects, rules and such here.

sleep 5

################################################################################################
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-simple-gateway <<.
{
  "name" : "gw-${1}",
  "color" : "RED",
  "ipv4-address" : "${IP}",
  "version" : "R77.30",
  "one-time-password" : "$otp",
  "firewall" : "true",
  "application-control" : "true",
  "url-filtering" : "true",
  "ips" : "true",
  "anti-bot" : "true",
  "anti-virus" : "true",
  "threat-emulation" : "true",
  "interfaces" : [ {
    "name" : "eth0",
    "ipv4-address" : "10.0.${subid}.254",
    "ipv4-mask-length" : "25",
    "anti-spoofing" : "false",
    "topology" : "EXTERNAL"
  }, {
    "name" : "eth1",
    "ipv4-address" : "10.0.${subid}.10",
    "ipv4-mask-length" : "25",
    "anti-spoofing" : "false",
    "topology" : "INTERNAL"
  } ]
}
.
 

sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-host <<.
{
  "name" : "ext-gw-${1}",
  "ip-address" : "10.0.${subid}.254"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-host <<.
{
  "name" : "app-${1}",
  "ip-address" : "10.0.${subid}.12"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-network <<.
{
  "name" : "$vpcid",
  "subnet" : "10.0.${subid}.0",
  "subnet-mask" : "255.255.255.0"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-network <<.
{
  "name" : "$subnetid0",
  "subnet" : "10.0.${subid}.0",
  "subnet-mask" : "255.255.255.128"
}
.


sleep 5

################################################################################################
# Publish and get out of here
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/publish

sleep 5

#Logout
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/logout

exit 0
