#!/bin/bash
if [ -z "$1" ]
  then
echo ""
    echo "Just give the number designation for the gateway, like $0 1"
    echo "This will build policy"
echo ""
exit
fi

source VAR
vpcid=$(awk '/VpcId/ {print $2;}' ${out}/${1}/vpc | sed 's/"//g' | sed 's/,//g')
subnetid0=$(awk '/SubnetId/ {print $2;}' ${out}/${1}/subnet0 | sed 's/"//g' | sed 's/,//g')
IP=$(awk '/PublicIpAddress/ {print $2;}' ${out}/${1}/pubip | sed 's/"//g' | sed 's/,//g')
baseurl=https://$host/web_api
curl_cmd="curl --silent --insecure -X POST"

SID=`${curl_cmd} -H "Content-Type: application/json" -d @- $baseurl/login <<. | awk -F\" '/sid/ {print $4}'
{
  "user":"$username" ,
  "password":"$password" ,
  "session-name":"API Delete Objects"
}
.`
# Login complete, add objects, rules and such here.

sleep 5

################################################################################################

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-host <<.
{
  "name" : "ext-gw-${1}",
  "ignore-warnings" : "true"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-host <<.
{
  "name" : "app-${1}",
  "ignore-warnings" : "true"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-network <<.
{
  "name" : "$vpcid",
  "ignore-warnings" : "true"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-network <<.
{
  "name" : "$subnetid0",
  "ignore-warnings" : "true"
}
.


sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-simple-gateway <<.
{
  "name" : "gw-${1}",
  "ignore-warnings" : "true"
}
.
 

sleep 5

################################################################################################
# Publish and get out of here
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/publish
#Logout
sleep 12
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/logout
