#!/bin/bash
source VAR
baseurl=https://$host/web_api
curl_cmd="curl --silent --insecure -X POST"

SID=`${curl_cmd} -H "Content-Type: application/json" -d @- $baseurl/login <<. | awk -F\" '/sid/ {print $4}'
{
  "user":"$username" ,
  "password":"$password" ,
  "session-name":"query"
}
.`
# Login complete, add objects, rules and such here.
################################################################################################

 
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-rule <<.
{
  "layer" : "Network",
  "position" : {"below" : "Kill em all"},
  "name" : "ssh Access",
  "source" : "$admin_host",
  "service" : "ssh_version_2",
  "action" : "Accept",
  "track" : "Full Log",
  "install-on" : "Policy Targets"
}
.


 
################################################################################################
# Publish and get out of here
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/publish
#Logout
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/logout
