#!/bin/bash
source VAR
vpcid=$(awk '/VpcId/ {print $2;}' ${out}/${1}/vpc | sed 's/"//g' | sed 's/,//g')
subnetid0=$(awk '/SubnetId/ {print $2;}' ${out}/${1}/subnet0 | sed 's/"//g' | sed 's/,//g')
IP=$(awk '/PublicIpAddress/ {print $2;}' ${out}/${1}/pubip | sed 's/"//g' | sed 's/,//g')
username="admin"
password="TheRainInSpain"
host="demo.mg.killhup.cx"
baseurl=https://$host/web_api
curl_cmd="curl --silent --insecure -X POST"

SID=`${curl_cmd} -H "Content-Type: application/json" -d @- $baseurl/login <<. | awk -F\" '/sid/ {print $4}'
{
  "user":"$username" ,
  "password":"$password" ,
  "session-name":"API"
}
.`
# Login complete, add objects, rules and such here.
################################################################################################
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-simple-gateway <<.
{
  "name" : "gw-${1}",
  "color" : "RED",
  "ipv4-address" : "${IP}",
  "version" : "R77.30",
  "one-time-password" : "avpn1234",
  "firewall" : true,
  "application-control" : true,
  "url-filtering" : true,
  "ips" : true,
  "anti-bot" : true,
  "anti-virus" : true,
  "threat-emulation" : true,
  "interfaces" : [ {
    "name" : "eth0",
    "ipv4-address" : "10.0.${1}.254",
    "ipv4-mask-length" : "25",
    "anti-spoofing" : "false",
    "topology" : "EXTERNAL"
  }, {
    "name" : "eth1",
    "ipv4-address" : "10.0.${1}.10",
    "ipv4-mask-length" : "25",
    "anti-spoofing" : "false",
    "topology" : "INTERNAL"
  } ]
}
.
 
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-host <<.
{
  "name" : "ext-gw-${1}",
  "ip-address" : "10.0.${1}.254"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-host <<.
{
  "name" : "app-${1}",
  "ip-address" : "10.0.${1}.12"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-network <<.
{
  "name" : "$vpcid",
  "subnet" : "10.0.${1}.0",
  "subnet-mask" : "255.255.255.0"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-network <<.
{
  "name" : "$subnetid0",
  "subnet" : "10.0.${1}.0",
  "subnet-mask" : "255.255.255.128"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-section <<.
{
  "layer" : "Network",
  "position" : "top",
  "name" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-rule <<.
{
  "layer" : "Network",
  "position" : "1",
  "name" : "${vpcid} App Access",
  "source" : "Any",
  "destination" : "ext-gw-${1}",
  "service" : "http",
  "action" : "Accept",
  "track" : "Full Log",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-rule <<.
{
  "layer" : "Network",
  "position" : "1",
  "name" : "${subnetid0} Outbound",
  "source" : "${subnetid0}",
  "destination" : "Any",
  "service" : "Any",
  "action" : "Accept",
  "track" : "Full Log",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-rule <<.
{
  "layer" : "Network",
  "position" : "1",
  "name" : "NTP Noise ${vpcid}",
  "source" : "${vpcid}",
  "destination" : "Any",
  "service" : "ntp",
  "action" : "Accept",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-rule <<.
{
  "layer" : "Network",
  "position" : "1",
  "name" : "DNS Noise ${vpcid}",
  "source" : "${vpcid}",
  "destination" : "${vpcid}",
  "service" : "dns",
  "action" : "Accept",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-access-section <<.
{
  "package" : "standard",
  "position" : "top",
  "name" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-nat-rule <<.
{
  "package" : "standard",
  "position" : { "below" : "gw-${1}" },
  "enabled" : "true",
  "original-source" : "${subnetid0}",
  "translated-source" : "ext-gw-${1}",
  "method" : "hide",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-nat-rule <<.
{
  "package" : "standard",
  "position" : { "below" : "gw-${1}" },
  "enabled" : "true",
  "original-service" : "http",
  "original-destination" : "ext-gw-${1}",
  "translated-destination" : "app-${1}",
  "method" : "static",
  "install-on" : "gw-${1}"
}
.

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/add-nat-rule <<.
{
  "package" : "standard",
  "position" : { "below" : "gw-${1}" },
  "enabled" : "true",
  "original-source" : "${vpcid}",
  "original-destination" : "${vpcid}",
  "install-on" : "gw-${1}"
}
.

################################################################################################
# Publish and get out of here
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/publish
#Logout
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/logout
