#!/bin/bash

if [ -z "$1" ]
  then
echo ""
    echo "Going to need active VPC names to remove load balance ex.: $0 <name> <name2> etc. . . "
echo ""
exit
fi

# lets rock!
. VAR
# get the list of secured app gateways
#
sites=( $@ )
len=${#sites[@]}
last=${sites[$len-1]}
count=`expr $len - 2`
lastsite=$(awk '/PublicIpAddress/ {print $2;}' ${out}/$last/pubip | sed 's/"//g' | sed 's/,//g')

if [ $use_dns = "true" ]
then
echo "{" > ${aplb}
echo "\"Comment\": \"${domain} DNS change \"," >> ${aplb}
echo "       \"Changes\": [" >> ${aplb}
echo "            {" >> ${aplb}
echo " \"Action\": \"DELETE\"," >> ${aplb}
echo "\"ResourceRecordSet\": {" >> ${aplb}
echo "\"Name\": \"app.${domain}\"," >> ${aplb}
echo "\"Type\": \"A\"," >> ${aplb}
echo "\"TTL\": 10," >> ${aplb}
echo "\"ResourceRecords\": [" >> ${aplb}
for (( i=0; i<=$count; i++ ))
do
lbip=$(awk '/PublicIpAddress/ {print $2;}' ${out}/${sites[$i]}/pubip | sed 's/"//g' | sed 's/,//g')
echo "            {\"Value\": \"$lbip\"}, " >> ${aplb}
done
echo "            {\"Value\": \"$lastsite\"} " >> ${aplb}
echo "         ]" >> ${aplb}
echo "      }" >> ${aplb}
echo "    }" >> ${aplb}
echo "  ]" >> ${aplb}
echo "}" >> ${aplb}

aws route53 change-resource-record-sets --hosted-zone-id $hostedid --change-batch file://${aplb}
echo "Removing VPCs at ${sites[@]} as app.${domain}" 
echo "shutdown of traffic in . . . "
for i in {10..1}
do
echo -n "${i}"
sleep .33
echo -n "."
sleep .33
echo -n "."
sleep .33
done
echo ". . . "
sleep 1
echo "app.${domain} offline." 
rm -rf ${app}/domain
exit
fi
echo "uhmmmm . . . you don't have hosted dns in route53, this won't work."
exit
