#!/bin/bash
# 
# test for input
#
if [ -z "$1" ]
  then
echo ""
    echo "give a name: $0 blah"
echo ""
exit
fi
#
# Set some system variables
source VAR
echo "$0 on ${1}" >> /tmp/auto.job
#
client_region=(`cat ${appout}/client/${1}.region`)
#
# launch script
#
#
#
echo "Killing."
#
Instance=$(awk '/InstanceId/ {print $2;}' ${appout}/client/${1}.json | sed 's/"//g' | sed 's/,//g')
#
IP=$(awk '/PublicIpAddress/ {print $2;}' ${appout}/client/${1}.json | sed 's/"//g' | sed 's/,//g')
baseurl=https://$host/web_api
curl_cmd="curl --silent --insecure -X POST"

# tag the instances so we can identify it
#
$cmd create-tags --region $client_region --tags Key=Name,Value=dead --resources $Instance
echo "Tagging $Instance as dead"
sleep 2
$cmd terminate-instances --region $client_region --instance-ids $Instance
sleep 1
#
# let the user know whats happened
#
echo " "
echo "checking client state . .  "
sleep 2
$cmd describe-instances --region $client_region --instance-ids $Instance | grep Value
echo "client $1 destroyed"
#
SID=`${curl_cmd} -H "Content-Type: application/json" -d @- $baseurl/login <<. | awk -F\" '/sid/ {print $4}'
{
  "user":"$username" ,
  "password":"$password" ,
  "session-name":"client removal"
}
.`

sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d @- $baseurl/delete-host <<.
{
  "name" : "${1}"
}
.

sleep 5

${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/publish
sleep 5
#Logout
${curl_cmd} -H "Content-Type: application/json" -H "X-chkp-sid: $SID" -d "{}" $baseurl/logout


# set launch time and cleanup before exit
#
rm -rf ${appout}/client/${1}.json
rm -rf ${appout}/client/${1}.region
#
echo " -> $0 ${1} COMMAND COMPLETE || "
cat /tmp/auto.job | grep -v "$0 on ${1}" > /tmp/${1}.done
mv /tmp/${1}.done /tmp/auto.job
exit 0

