#!/bin/bash
# test for input
if [ -z "$1" ]
  then
echo ""
    echo "Just give the number designation for the vpc, like $0 101"
    echo "This will create the app to attach to the secure subnet."
echo ""
exit
fi
source VAR
if [ ! -d "${out}/${1}" ] ; then
echo "no no vpc called ${1} to launch into"
echo ""
exit
fi

echo "$0 on ${1}" >> /tmp/auto.job

appregion=(`cat ${out}/${1}/region`)
subid=(`cat ${out}/${1}/id`)
rm -rf ${appinit_launch}.gz

echo "region set to: $appregion"
if [ "$appregion" = "us-east-1" ] 
then
ami="$eappami" 
keyname="$ekeyname"
else
# region is west be west, change or add in VAR (run cpconfig)
ami="$wappami"
keyname="$wkeyname"
fi
# here we go
vpcid=$(awk '/VpcId/ {print $2;}' ${appout}/$1/vpc | sed 's/"//g' | sed 's/,//g')
subnetid=$(awk '/SubnetId/ {print $2;}' ${appout}/$1/subnet0 | sed 's/"//g' | sed 's/,//g')
echo "Create app $1"
rm -rf ${appout}/${1}/app-${1}.dead
cat $apphead > $appinit_launch
echo "hostname app-${1}" >> $appinit_launch
echo "echo \"This data delivered by app-${1} in $subnetid as part of $vpcid protected by ${1}.${domain} \" > /tag" >> $appinit_launch
cat $apptail >> $appinit_launch
gzip $appinit_launch
# init script prepped, launch instance with it
# launch script
$cmd run-instances --region $appregion --image-id $ami --key-name $keyname --user-data fileb://${appinit_launch}.gz --instance-type $appinstancetype --subnet-id $subnetid --private-ip-address 10.0.${subid}.12 --block-device-mappings file://${appdisk} > ${appout}/${1}/app-${1}.json 
echo "Initalizing."
sleep 5
Instance=$(awk '/InstanceId/ {print $2;}' ${appout}/${1}/app-${1}.json | sed 's/"//g' | sed 's/,//g')
$cmd create-tags --region $appregion --tags Key=Name,Value=app-${1} --resources $Instance
echo "Tagging $Instance as app $1"
IP=$(awk '/PrivateIpAddress/ {print $2;}' ${appout}/${1}/app-${1}.json | sed 's/"//g' | sed 's/,//g' |  sed -e '4!d')
echo " app-$1 is $Instance using $IP"
blastoff=$(date)
$cmd describe-instances --region $appregion --instance-ids $Instance
echo "app-$1 deployed"
echo "$Instance launched at $blastoff, app-$1 services are deployed."
rm -rf ${appinit_launch}.gz
echo " -> $0 ${1} COMMAND COMPLETE || "
cat /tmp/auto.job | grep -v "$0 on ${1}" > /tmp/${1}.done
mv /tmp/${1}.done /tmp/auto.job
exit 0

