#!/bin/bash

# lets rock!
. VAR
#vpc_active=(`ls ${gwout}/*/natuids 2> /dev/null | cut -d/ -f5`)
app_active=(`find ${out}/*/app*.json -mmin +3 2> /dev/null | cut -d/ -f5 | cut -d. -f1`)
if [ -z "${app_active}" ] ; then
	echo "can't find sites to load balance"
		exit
		fi
        echo -n "${app_active[@]}"
echo -n "Active sites detected: ${app_active[@]}"
# get the list of secured app gateways
#
sites=( ${app_active[@]} )
len=${#sites[@]}
if [ "$len" < 2 ]; then
	echo "Not enought active sites to load share anything"
	echo
	exit
fi

last=${sites[$len-1]}
count=`expr $len - 2`
lastsite=$(awk '/PublicIpAddress/ {print $2;}' ${out}/$last/pubip | sed 's/"//g' | sed 's/,//g')

if [ $use_dns = "true" ]
then
echo "{" > ${aplb}
echo "\"Comment\": \"${domain} DNS change \"," >> ${aplb}
echo "       \"Changes\": [" >> ${aplb}
echo "            {" >> ${aplb}
echo " \"Action\": \"UPSERT\"," >> ${aplb}
echo "\"ResourceRecordSet\": {" >> ${aplb}
echo "\"Name\": \"app.${domain}\"," >> ${aplb}
echo "\"Type\": \"A\"," >> ${aplb}
echo "\"TTL\": 10," >> ${aplb}
echo "\"ResourceRecords\": [" >> ${aplb}
for (( i=0; i<=$count; i++ ))
do
lbip=$(awk '/PublicIpAddress/ {print $2;}' ${out}/${sites[$i]}/pubip | sed 's/"//g' | sed 's/,//g')
echo "            {\"Value\": \"$lbip\"}, " >> ${aplb}
done
echo "            {\"Value\": \"$lastsite\"} " >> ${aplb}
echo "         ]" >> ${aplb}
echo "      }" >> ${aplb}
echo "    }" >> ${aplb}
echo "  ]" >> ${aplb}
echo "}" >> ${aplb}

aws route53 change-resource-record-sets --hosted-zone-id $hostedid --change-batch file://${aplb}
echo "setting VPCs at ${sites[@]} as app.${domain}" 
echo "Load balancing of traffic in . . . "
for i in {10..1}
do
echo -n "${i}"
sleep .33
echo -n "."
sleep .33
echo -n "."
sleep .33
done
echo ". . . "
sleep 1
echo "app.${domain} active." 
echo "app.${domain} directed to ${sites[@]}" > ${app}/domain
exit
fi
echo "uhmmmm . . . you don't have hosted dns in route53, this won't work."
exit
