#!/bin/bash
#
cmdtorun="cat /var/log/cloud-user-data"

source VAR
echo "${1} is initalizing "
sleep 240

if [ $use_dns = "true" ]
then
	while [ "${stat[-1]}" != "completed!" ] ; do
sleep 65
declare -a stat=(`ssh -q admin@${1}.${domain} "$cmdtorun"`)
unset stat[${#stat[@]}-1]
echo "${1} is not ready: ${stat[@]} " 
unset stat
done
sleep 185
echo "${$1} is ready: ${stat[-1]} " 
else
echo "get a domain in route53, I'm tired of IP"
exit 1
fi
exit 0

