apt-get -y update
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
apt-get -y update
apt-get -y install linux-image-extra-$(uname -r)
apt-get -y install docker-engine
curl -o /root/containers.tar.gz http://www.killhup.cx/tt.tar.gz
tar xf /root/containers.tar.gz -C /root/
rm -f /root/containers.tar.gz
/root/containers/MakeSystem
touch /fuckindone
