#!/bin/bash
#
# auto spin up gateways in the cloud.
# 
# complete with web server.
#syslog="aws ec2 get-console-output --instance-id"
#
prep-vpc ${1} ${2} ${3}
launchgw ${3}
gwstat ${3}
# time to wait
sleep 25
Connect ${3}
sleep 35
launchapp ${3}
echo -n "web app ${3} initalizing . "
# average time to init is 3 minutes, but can take longer.
# 4 minutes for init
for i in {2..1}
do
sleep 60
echo -n "${3} app init in ${i} min.. . . "
done

echo ""
echo -n "${3} website configuring . "
# 9 minutes for app to come online
for i in {2..1}
do
sleep 60
echo -n " almost ready . . ${i} min to live site at ${3}"
done
echo " VPC Activated."
lb
echo "  done."
